---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi-cephfs
stringData:
  userID: admin
  userKey: AQBUHsxmopo/BRAAF/ei6E80+HiHRzJY3Jtjaw==

  adminID: admin
  adminKey: AQBUHsxmopo/BRAAF/ei6E80+HiHRzJY3Jtjaw==

